env:
  - DEP_VERSION="0.5.0"

jobs:
  include:
    - stage: tests
      language: go
      go:
        - "1.x"
        - "1.10.x"
        - master
      services:
        - postgresql
      before_install:
        - cp .env.travis .env
        # Download the binary to bin folder in $GOPATH
        - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
        # Make the binary executable
        - chmod +x $GOPATH/bin/dep
      install:
        - make prepare
      before_script:
        - psql -c 'create database travis_lexic_test;' -U postgres
      script:
        - make test