// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	time "time"
)

type HostReq struct {
	Name     string  `json:"name"`
	Password *string `json:"password"`
}

type Info struct {
	Version string `json:"version"`
}

type NewUser struct {
	Name      string     `json:"name"`
	FirstName string     `json:"firstName"`
	LastName  string     `json:"lastName"`
	Email     string     `json:"email"`
	Password  string     `json:"password"`
	Birthday  *time.Time `json:"birthday"`
}
